### ISSUE TITLE
help me reset the form

### ISSUE THREAD

**Issue by Boby900** [Boby900/yogurt#4]
Hi there,
I am trying to reset the form input fields after submitting the form but I am not able to, I am using `server action` for getting data out of input fields.

Any help would be greatly appreciated.
Also feel free to submit the PR if you find anything broken or any type of enhancement.

![Screenshot (537)](https://github.com/Boby900/yogurt/assets/111265239/8cdca569-f8fd-4e3f-9fce-9baf085f38c9)

**Comment by AtharvaChobe** [comment]
I can work on this. Please can you assign this to me?

**Comment by Boby900** [comment]
Hi @AtharvaChobe ,
I have assigned this to you
